<?php

namespace App\Http\Controllers;

use App\Models\Voucher;
use App\Models\ChartOfAccounts;
use App\Models\Customer;
use App\Models\Vendor;
use App\Services\VoucherService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class VoucherController extends Controller
{
    public function __construct(private VoucherService $voucherService) {}

    private function validTypes(): array
    {
        return ['journal', 'payment', 'receipt', 'contra'];
    }

    public function index(string $type)
    {
        abort_unless(in_array($type, array_merge($this->validTypes(), ['system'])), 404);

        $vouchers = Voucher::with('entries.account')
            ->where('type', $type)
            ->orderByDesc('voucher_date')
            ->orderByDesc('id')
            ->get();

        return view('vouchers.index', compact('vouchers', 'type'));
    }

    public function create(string $type)
    {
        abort_unless(in_array($type, $this->validTypes()), 404);

        $accounts  = ChartOfAccounts::active()->orderBy('account_code')->get();
        $customers = Customer::active()->orderBy('name')->get();
        $vendors   = Vendor::active()->orderBy('name')->get();

        return view('vouchers.create', compact('type', 'accounts', 'customers', 'vendors'));
    }

    public function store(Request $request, string $type)
    {
        abort_unless(in_array($type, $this->validTypes()), 404);

        $request->validate([
            'voucher_date'          => 'required|date',
            'narration'             => 'nullable|string|max:500',
            'lines'                  => 'required|array|min:2',
            'lines.*.account_id'    => 'required|exists:chart_of_accounts,id',
            'lines.*.debit'         => 'nullable|numeric|min:0',
            'lines.*.credit'        => 'nullable|numeric|min:0',
            'lines.*.party_type'    => 'nullable|in:customer,vendor',
            'lines.*.party_id'      => 'nullable|integer',
        ]);

        try {
            $lines = collect($request->lines)->map(fn($l) => [
                'account_id' => $l['account_id'],
                'debit'      => $l['debit']  ?? 0,
                'credit'     => $l['credit'] ?? 0,
                'party_type' => $l['party_type'] ?? null,
                'party_id'   => $l['party_id']   ?? null,
            ])->toArray();

            $voucher = $this->voucherService->post(
                $type,
                $request->voucher_date,
                $lines,
                $request->narration,
                null,
                null,
                auth()->id()
            );

            Log::info('[Voucher] Created', ['id' => $voucher->id, 'type' => $type, 'by' => auth()->id()]);

            return redirect()->route('vouchers.index', $type)
                ->with('success', 'Voucher ' . $voucher->voucher_no . ' posted successfully.');

        } catch (\Exception $e) {
            Log::error('[Voucher] Store failed', ['message' => $e->getMessage()]);
            return back()->withInput()->with('error', $e->getMessage());
        }
    }

    public function show(string $type, $id)
    {
        $voucher = Voucher::with('entries.account', 'entries.party')->findOrFail($id);

        return response()->json([
            'voucher_no' => $voucher->voucher_no,
            'date'       => $voucher->voucher_date->format('Y-m-d'),
            'narration'  => $voucher->narration,
            'entries'    => $voucher->entries->map(fn($e) => [
                'account_name' => $e->account->name ?? '—',
                'party_name'   => $e->party->name ?? null,
                'debit'        => (float) $e->debit,
                'credit'       => (float) $e->credit,
            ]),
        ]);
    }

    public function destroy(string $type, $id)
    {
        try {
            $voucher = Voucher::findOrFail($id);

            if ($voucher->reference_type) {
                return back()->with('error',
                    'This voucher was auto-generated by ' . $voucher->reference_type .
                    '. Delete/reverse that record instead.');
            }

            $voucher->entries()->delete();
            $voucher->delete();

            Log::info('[Voucher] Deleted', ['id' => $id, 'by' => auth()->id()]);

            return redirect()->route('vouchers.index', $type)->with('success', 'Voucher deleted successfully.');

        } catch (\Exception $e) {
            Log::error('[Voucher] Destroy failed', ['id' => $id, 'message' => $e->getMessage()]);
            return back()->with('error', 'Could not delete voucher.');
        }
    }
}